name: Kafka for Baking Sample Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE }}
        role-session-name: GitHubActionsRole
        aws-region: us-east-1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: setup
    env:
      AWS_REGION: us-east-1
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan -out=tfplan
    
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    env:
      AWS_REGION: us-east-1
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan
    
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
    
    - name: Post Success Message
      run: echo "We did it!!"
